### ISSUE TITLE
Проверить смысл фразы

### ISSUE THREAD

**Issue by modox94** [crazynike94/Little-Witch-Academia#1]
Такиючи говорит, что у его компании 20 кадров. Что за компания такая? Разве он не из триггера? Плюс хорошо бы удостовериться, что он ассистент продюсера, а не продашна. Я везде на продюсера поменял, но меня чутка терзают сомнения. Вот скрин момента, который меня беспокоит и копия ансаба.

![_ 6 2017 _11h06m17s_003](https://user-images.githubusercontent.com/25570057/27901586-435d33e6-623b-11e7-95a6-e6fb8f9c0516.png)

Dialogue: 0,0:34:02.27,0:34:04.11,Default,,0,0,0,,I'm a mess.
Dialogue: 0,0:34:05.74,0:34:08.01,Default,,0,0,0,,I'm gone.
Dialogue: 0,0:34:10.34,0:34:11.81,Default,,0,0,0,,(I don't blame you...)
Dialogue: 0,0:34:11.81,0:34:14.32,Default,,0,0,0,,Today's the last day.
Dialogue: 0,0:34:15.75,0:34:17.29,Default,,0,0,0,,(How much is left?)
Dialogue: 0,0:34:18.95,0:34:23.82,Default,,0,0,0,,About 20 cuts left in our company.\NStill working on it.
Dialogue: 0,0:34:24.49,0:34:25.26,Default,,0,0,0,,Yeah...
Dialogue: 0,0:34:26.49,0:34:30.50,Default,,0,0,0,,I hope to have these checked off by 6am.
Dialogue: 0,0:34:32.33,0:34:35.27,Default,,0,0,0,,Only 9 hours left until the deadline.

**Comment by modox94** [comment]
Вот. Дальше он ходит между аниматорами триггера. Думаю компанию надо заменить на команду или типа того.
А то хуйня выходит.

![_ 6 2017 _11h19m05s_005](https://user-images.githubusercontent.com/25570057/27902051-efe55af2-623c-11e7-9798-9ba7b1d4d4db.png)

**Comment by eugene815** [comment]
> что у его компании 
у нас

**Comment by modox94** [comment]
Так?
![the making of little witch academia the enchanted parade_001_61714](https://user-images.githubusercontent.com/25570057/27911281-3233e7b0-6261-11e7-942c-ea8c89dcc173.png)
