### ISSUE TITLE
Проверить имя

### ISSUE THREAD

**Issue by modox94** [crazynike94/Little-Witch-Academia#2]
Сакамото? Ансаб такой же. Мне кажется, что Сакамото и Исида Кадзумаса все-таки разные люди, лол. Может быть я просто не понимаю чего-то.
![the making of little witch academia the enchanted parade_001_63113](https://user-images.githubusercontent.com/25570057/27902575-e52e0800-623e-11e7-88d3-1c1ebfe512d1.png)
![the making of little witch academia the enchanted parade_002_63113](https://user-images.githubusercontent.com/25570057/27902574-e52bbe6a-623e-11e7-9dfb-2a1f2f112d38.png)

Тайминг: 0:35:05

**Comment by eugene815** [comment]
石田(ishida)一将(kazumasa)
Все верно.
