### ISSUE TITLE
Надпись

### ISSUE THREAD

**Issue by modox94** [crazynike94/Little-Witch-Academia#3]
Надпись
![the making of little witch academia the enchanted parade_001_65908](https://user-images.githubusercontent.com/25570057/27903465-20cad30e-6242-11e7-835a-f170d44bebce.png)

Тайминг: 0:36:39

**Comment by eugene815** [comment]
スタジオ*ミュウ
東京 練馬
Студия ミュウ(Mew? Мьюу? Мюу?)
Токио, Нэрима

**Comment by modox94** [comment]
https://ru.wikipedia.org/wiki/Мью_(покемон)
Точно такое же написание, хех.
